### ISSUE TITLE
Wrong files pushed for version 0.0.2 on npm

### ISSUE THREAD

**Issue by jleskovar** [vinayakkulkarni/vuejs-datatables-sui#1]
vuejs-datatables-sui 0.0.2 on npm looks like it still contains bootstrap template in template.js

**Comment by jleskovar** [comment]
Download: https://registry.npmjs.org/vuejs-datatables-sui/-/vuejs-datatables-sui-0.0.2.tgz

Open up package/compiled/template.js

Table template still contains twbs classes - e.g. "col-md-6"

**Comment by jleskovar** [comment]
test
    and

**Comment by vinayakkulkarni** [comment]
Actually I'm bit busy with RL, would appreciate a PR if you've got the time...

**Comment by jleskovar** [comment]
I don't think this can be fixed with a PR, can it? It looks like you just need to publish the correct files. The actual template.js in the repository itself looks correct.

**Comment by jleskovar** [comment]
It's not urgent since I can always just refer to the git repo in my package.json

**Comment by vinayakkulkarni** [comment]
Can you check it now? I published a v. 0.0.3 on npm

commit: 958cc6b6dcbb956bff47b8be1aeeea7abca92769

**Comment by vinayakkulkarni** [comment]
Feel free to close it if you think it's resolved ⚡️

**Comment by jleskovar** [comment]
Yep, looks like it is all good now. Thanks for the quick turnaround!
